[env:lilygo-t-sim7080]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Serial Monitor Settings
monitor_speed = 115200
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BOARD_HAS_PSRAM

; Flash and PSRAM settings for the LilyGo S3
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_upload.flash_size = 16MB

; Library Dependencies (Automatic Download)
lib_deps =
    vshymanskyy/TinyGSM @ ^0.11.7
    vshymanskyy/StreamDebugger @ ^1.0.1
    arduino-libraries/ArduinoHttpClient @ ^0.6.0
    adafruit/Adafruit BME280 Library @ ^2.2.4
